  /*
   * Test written manually.
   * This is a unit test that always succeeds.
   */

import static org.junit.Assert.assertEquals;
import org.junit.Test;
import com.diffblue.tictactoe.TicTacToe;

public class TicTacToeTest {

  @Test
  public void test() throws Exception {
    assertEquals(0, 0);
  }


  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

//  @PrepareForTest({tictactoe.class, System.class})
  @Test
  public void displayHelp000c329d8c1bf87f0c0() throws Exception {
    // Act
    TicTacToe.displayHelp();
    // Method returns void, testing that no exception is thrown 
  }

  
  /* testedClasses: com/diffblue/tictactoe/tictactoe.java */
  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void constructor30007762b8bf14a240e9() {

    // Act, creating object to test constructor
    final TicTacToe objectUnderTest = new TicTacToe();

    // Method returns void, testing that no exception is thrown
  }

}
