/*
 * This is a unit test that always succeeds.
 * It was written manually
 */

import static org.junit.Assert.assertEquals;
import org.junit.Test;

public class tictactoeTest {

  @Test
  public void test() throws Exception {
    assertEquals(0, 0);
  }


// ---------------------------

/*
 * Test generated by Diffblue Deeptest.
 * This test case covers the entire method.
 */

//  @PrepareForTest({tictactoe.class, System.class})
  @Test
  public void displayHelp000c329d8c1bf87f0c0() throws Exception {
    // Act
    tictactoe.displayHelp();
    // Method returns void, testing that no exception is thrown 
  }

}
